version: "3"
services:
  mgbuild_centos-7:
    build:
      context: centos-7
    container_name: "mgbuild_centos-7"
  mgbuild_centos-9:
    build:
      context: centos-9
    container_name: "mgbuild_centos-9"
  mgbuild_debian-10:
    build:
      context: debian-10
    container_name: "mgbuild_debian-10"
  mgbuild_debian-11:
    build:
      context: debian-11
    container_name: "mgbuild_debian-11"
  mgbuild_ubuntu-18.04:
    build:
      context: ubuntu-18.04
    container_name: "mgbuild_ubuntu-18.04"
  mgbuild_ubuntu-20.04:
    build:
      context: ubuntu-20.04
    container_name: "mgbuild_ubuntu-20.04"
  mgbuild_ubuntu-22.04:
    build:
      context: ubuntu-22.04
    container_name: "mgbuild_ubuntu-22.04"
  mgbuild_fedora-36:
    build:
      context: fedora-36
    container_name: "mgbuild_fedora-36"
  mgbuild_amzn-2:
    build:
      context: amzn-2
    container_name: "mgbuild_amzn-2"
