header: >-
  Memgraph Configuration

  This is the main configuration file for Memgraph. You can modify this file to
  suit your specific needs. Additional configuration can be specified by
  including another configuration file, in a file pointed to by the
  'MEMGRAPH_CONFIG' environment variable or by passing arguments on the command
  line.

  Each configuration setting is in the form: '--setting-name=value'.

footer: >-
  Additional Configuration Inclusion

  You can include additional configuration files from this file. Additional
  files are processed after this file. Settings that are set in the additional
  files will override previously set values. Additional configuration files are
  specified with the '--flag-file' flag.

  Example:

  --flag-file=another.conf

modifications:

  # Each modification should consist of the following parameters:
  #   * name: the name of the flag that should be modified (with underscores)
  #           [string]
  #   * value: the value that should be set instead of the binary provided
  #            default value [string]
  #   * override: set to `true` to uncomment the config option by default
  #               [boolean]

  - name: "data_directory"
    value: "/var/lib/memgraph"
    override: true

  - name: "log_file"
    value: "/var/log/memgraph/memgraph.log"
    override: true

  - name: "log_level"
    value: "WARNING"
    override: true

  - name: "bolt_num_workers"
    value: ""
    override: false

  - name: "bolt_cert_file"
    value: "/etc/memgraph/ssl/cert.pem"
    override: false

  - name: "bolt_key_file"
    value: "/etc/memgraph/ssl/key.pem"
    override: false

  - name: "storage_properties_on_edges"
    value: "true"
    override: true

  - name: "data_recovery_on_startup"
    value: "true"
    override: true

  - name: "storage_snapshot_interval_sec"
    value: "300"
    override: true

  - name: "storage_snapshot_on_exit"
    value: "true"
    override: true

  - name: "storage_snapshot_retention_count"
    value: "3"
    override: true

  - name: "storage_wal_enabled"
    value: "true"
    override: true

  - name: "telemetry_enabled"
    value: "true"
    override: true

  - name: "query_modules_directory"
    value: "/usr/lib/memgraph/query_modules"
    override: true

  - name: "auth_module_executable"
    value: "/usr/lib/memgraph/auth_module/example.py"
    override: false

  - name: "memory_limit"
    value: "0"
    override: true

  - name: "isolation_level"
    value: "SNAPSHOT_ISOLATION"
    override: true

  - name: "storage_mode"
    value: "IN_MEMORY_TRANSACTIONAL"
    override: true

  - name: "allow_load_csv"
    value: "true"
    override: false

  - name: "storage_parallel_index_recovery"
    value: "false"
    override: true

  - name: "storage_parallel_schema_recovery"
    value: "false"
    override: true

  - name: "storage_enable_schema_metadata"
    value: "false"
    override: true

  - name: "storage_automatic_label_index_creation_enabled"
    value: "false"
    override: true

  - name: "storage_automatic_edge_type_index_creation_enabled"
    value: "false"
    override: true

  - name: "storage_enable_edges_metadata"
    value: "false"
    override: true

  - name: "query_callable_mappings_path"
    value: "/etc/memgraph/apoc_compatibility_mappings.json"
    override: true

undocumented:
  - "flag_file"
  - "also_log_to_stderr"
  - "help"
  - "help_xml"
  - "version"
  - "organization_name"
  - "license_key"
