name: "Diff MGCXX"

on:
  workflow_call:
    inputs:
      run_test:
        type: boolean
        description: "Should the mgcxx tests be run? Default is true."
        default: true
      ref:
        description: 'Branch or commit ref to run the workflow on'
        required: false
        default: ''
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  MGCXXTest:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_test == true }}
    name: "Test MGCXX"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        ref: ${{ inputs.ref || github.ref }}
        fetch-depth: 0

    - name: Build and unit test
      run: |
        cd mgcxx
        mkdir build && cd build
        cmake .. && make -j$(nproc)
        ctest
